build:
  image: bjodah/scipy-2017-codegen-tutorial
  environment:
    - CONDA_BLD_PATH=/root/conda-bld
  commands:
    - export PATH=/opt/miniconda3/bin:$PATH
    - conda build conda-recipe/
    - conda env create --quiet -f environment.yml
    - bin/render_notebooks.sh
    - mkdir deploy
    - cp intro-slides/* deploy/
    - mv notebooks/*.html deploy/
    - mv notebooks/*.nbconvert.ipynb deploy/
    - mkdir $CONDA_BLD_PATH
    - anaconda -t $$ANACONDA_TOKEN upload -u sympy --force $CONDA_BLD_PATH/linux-64/*.tar.bz2

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: scipy-2017-codegen-tutorial
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
