build:
  image: bjodah/scipy-2017-codegen-tutorial
  environment:
    - CONDA_BLD_PATH=/root/conda-bld
  commands:
    - sed -i '$ d' environment.yml
    - conda env create --quiet -f environment.yml
    - bin/render_notebooks.sh
    - bin/prepare_deploy.sh
    - mkdir $CONDA_BLD_PATH
    - conda build conda-recipe/
    - anaconda -t ${ANACONDA_TOKEN} upload --quiet -u sympy --force $CONDA_BLD_PATH/linux-64/*.tar.bz2
    - cp $CONDA_BLD_PATH/linux-64/*.tar.bz2 deploy/

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: scipy-2017-codegen-tutorial
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
