name: codegen17
channels:
  - sympy
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - nbconvert
  - numpy
  - matplotlib
  - scipy
  - cython
  - theano
  - sympy
  - sundials
  - numba
  - mingw
  - scipy2017codegen
