name: codegen17
channels:
  - symengine
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - nbconvert
  - numpy
  - matplotlib
  - scipy
  - cython
  - sympy
  - sundials
  - python-symengine
  - numba
